stages:
  - build
  - test
  - deploy

variables:
  SSH_PORT: "226"
  SSH_USER: "dev"
  SSH_HOST: "104.248.98.157"
  DEPLOY_PATH: "/home/dev/test/"
  SSH_KEY: "$SSH_PRIVATE_KEY"

default:
  tags:
  - local
  before_script:
    - pwd
    - echo $USER
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" | base64 --decode | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "StrictHostKeyChecking no" > ~/.ssh/config

build:
  stage: build
  script:
    - echo "Building the application..."
    - ls -la
    - scp "./test.sh" $SSH_USER@$SSH_HOST:$DEPLOY_PATH
    # Add your build commands here, for example:
    # - docker build -t your-image-name .

test:
  stage: test
  script:
    - echo "Running tests..."
    - ssh $SSH_USER@$SSH_HOST -p $SSH_PORT sh "$DEPLOY_PATH/test.sh"

deploy:
  stage: deploy
  script:
    - echo "Deploying to server..."