stages:
  - build
  - test
  - deploy

variables:
  SSH_PORT: "226"
  SSH_USER: "dev"
  SSH_HOST: "103.178.67.56"
  DEPLOY_PATH: "/home/dev/test/"

default:
  image: ubuntu:20.04

before_script:
  # setup ssh on host side
  - apt-get update -y && apt-get install -y openssh-client
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent -s)
  - ssh-add ~/.ssh/id_rsa
  - ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts

build:
  stage: build
  script:
    - echo "Building the application..."
    # Add your build commands here, for example:
    # - docker build -t your-image-name .

test:
  stage: test
  script:
    - echo "Running tests..."
    # Add your test commands here, for example:
    # - docker run your-image-name test_command

deploy:
  stage: deploy
  script:
    - echo "Deploying to server..."
    - ssh $SSH_USER@$SSH_HOST -p $SSH_PORT
    - ls -la
    - mkdir -p "$DEPLOY_PATH"
    - cd "$DEPLOY_PATH"
    - git clone "$CI_PROJECT_URL"
    - ls -la
  only:
    - main  # Deploy only from the main branch